package GFG;/*
 *
 * https://www.geeksforgeeks.org/problems/finding-profession3834/1
 *
 * # Finding Profession
 *
 *   Q. Consider a special family of Engineers and Doctors with following rules :
 *        ◦ Everybody has two children.
 *        ◦ First child of an Engineer is an Engineer and second child is a Doctor.
 *        ◦ First child of a Doctor is Doctor and second child is an Engineer.
 *        ◦ All generations of Doctors and Engineers start with Engineer.
 *
 *      The first few levels of the family tree are shown below :
 *                                                                     ( E )
 *                                                                   /       \
 *                                                                  /         \
 *                                                                (E)          (D)
 *                                                               /  \          /  \
 *                                                            (E)    (D)     (D)   (E)
 *                                                            / \    / \     /  \   / \
 *                                                          (E) (D)(D) (E) (D) (E)(E) (D)
 *
 *      Given level and position (pos) of a person in above ancestor tree, find profession of the person.
 *
 *    Ex.
 *      Input : level = 4, pos = 2
 *      Output: Doctor
 *      Explanation: It is shown in the tree given in question.
 *
 *  Constraints:
 *      1 ≤ level ≤ 10⁹
 *      1 ≤ pos ≤ 10⁹
 */

import java.util.Scanner;

public class POTD_Finding_Profession {

    /// main Method
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);

        System.out.print("Level: ");
        int level = sc.nextInt();

        System.out.print("Pos: ");
        int pos = sc.nextInt();

        System.out.print("Profession: ");
        System.out.println(profession(level, pos));
    }

    /// Solution
/*
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯-using-Recursion-⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
TC : O(log(pos))
SC : O(log(pos)) ---> recursive call stack
*/
    static String approach_1(int level, int pos) {
        // potd.code.hub
        if (level == 1 || pos == 1) return "Engineer";

        // recursive case
        String parent = approach_1(level - 1, (pos + 1) / 2);

        // self work
        if ((pos & 1) == 1) return parent;
        else return (parent.equals("Engineer") ? "Doctor" : "Engineer");
    }

/*
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯--Thue-Morse--Sequence--⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
TC : O(1)
SC : O(1)
*/
    static String profession(int level, int pos) {
        // potd.code.hub
        return (Integer.bitCount(pos - 1) & 1) == 1 ? "Doctor" : "Engineer";
    }
/*
    EDDEDEED
    EDDEDEEDDEEDEDDE
    EDDEDEEDDEEDEDDEDEEDEDDEEDDEDEED
    EDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDE
    ||||||||||
    EOOEOEEOOE --> set-bit count -- ODD (Doctor) / EVEN (Engineer)
    ||||||||||
    0123456789 --> position
    ||||||||||
    0000000000 --> binary representation
    0000000000
    0000000011
    0000111100
    0011001100
    0101010101

    The Thue-Morse sequence (also known as the Prouhet-Thue-Morse sequence) is a famous infinite binary sequence
    (a sequence of 0s and 1s) that never becomes periodic, meaning it contains no repeating patterns, yet it is
    completely predictable and generated by simple deterministic rules.

    It is highly regarded in mathematics, computer science, and physics because it appears naturally in combinations,
    game theory, fractal geometry, and even the problem you solved earlier regarding family trees.

    ex - 0 1 1 0 1 0 0 1 1 0 0 1 0 1 1 0 ...
*/
}
